export const MOCK_REQUESTS = [
  {
    id: 'r1',
    type: 'izin',
    className: 'CS101 — Struktur Data',
    studentName: 'Naila Putri',
    sessionDate: '2026-07-02',
    reason: 'Mengikuti lomba debat tingkat nasional yang diwakilkan oleh kampus.',
    attachmentUrl: '#',
    status: 'pending',
  },
  {
    id: 'r2',
    type: 'revisi',
    className: 'CS204 — Basis Data',
    studentName: 'Naila Putri',
    sessionDate: '2026-06-20',
    reason: 'Sistem mencatat alpa, padahal sudah presensi QR tapi sinyal lambat.',
    attachmentUrl: '#',
    status: 'approved',
  },
  {
    id: 'r3',
    type: 'izin',
    className: 'CS204 — Basis Data',
    studentName: 'Rangga Putra',
    sessionDate: '2026-06-18',
    reason: 'Sakit demam, surat dokter terlampir.',
    attachmentUrl: '#',
    status: 'rejected',
  },
  {
    id: 'r4',
    type: 'revisi',
    className: 'CS101 — Struktur Data',
    studentName: 'Dimas Aulia',
    sessionDate: '2026-06-15',
    reason: 'Mahasiswa keberatan dengan keputusan dosen, mengajukan eskalasi.',
    attachmentUrl: '#',
    status: 'escalated',
  },
]
